### ISSUE TITLE
Problematic constructor defaults

### ISSUE THREAD

**Issue by Pro100AlexHell** [splitice/QuadTrees#11]
First of all, I have spend a few hours to review your code and debug.
I have found:
1) QuadTreeRectF default constructor creates infinite box
`QuadTreePointRoot =
                CreateNode(new RectangleF(float.MinValue/2, float.MinValue/2, float.MaxValue, float.MaxValue));`
2) All additions to this QuadTreeRectF will NOT Subdivide because it's infinite box
screenshot with debug https://prnt.sc/qgydgi
as a result it will add all objects in the Root node
screenshot https://prnt.sc/qgye3u
3) plus your constant `MaxObjectsPerNode = 10;` does nothing
screenshot https://prnt.sc/qgye1v
i.e. 11 objects will appear at the Root
https://prnt.sc/qgx7wc
and 100 000 objects will appear at the Root
4) Query performs a full scan through Root with all of this 100k objects
causing a bad performance
.. perf with QuadTree is worse than if not use it at all, and foreach through a list of all objects manually

--------
I can't find any Unit Test, which will fill a Quad Tree with Subdivision
all of your tests creates not-normal Root without Subdivision

for example
your Unit Tests also does not specify this box parameter
```
        public static void TestAddMany()
        {
            Random r = new Random(1000);
            QuadTreeRectF<QTreeObject> qtree = new QuadTreeRectF<QTreeObject>();
            for (int i = 0; i < 10000; i++)
            {
                qtree.Add(new QTreeObject(new RectangleF(r.Next(0, 1000) / 1000f, r.Next(0, 1000) / 1000f, r.Next(1000, 20000) / 1000f, r.Next(1000, 20000) / 1000f)));
            }

            var result = qtree.GetObjects(new RectangleF(-100, -100, 200, 200));
            Assert.AreEqual(result.Distinct().Count(), result.Count);

            result = qtree.GetObjects(new RectangleF(-.100f, -.100f, .200f, .200f));
            Assert.AreEqual(result.Distinct().Count(), result.Count);
        }
```
and creates 10k objects inside Root
http://prntscr.com/qgytnh

and iterates through 10k by for-loop
http://prntscr.com/qgyu1x

------
last commit to this repo was in 2016
and all of this time, all of your users, use totally buggy implementation

-----
p.s. after a few hours I have found a case when Subdivision really works: in my project, I detect actual bounds of X and Y, and write constructor like
`new QuadTreeRectF<WorldObjectInQuadTree>(new System.Drawing.RectangleF(-8000, -8000, 16000, 16000));`
it's not good as we need to know exactly bounds

but it's work, i.e. assigns _childTl, _childTr , etc.

but performance is terrible..
100k objects is populates a few minutes into QuadTree
after that initial population, objects start to moving and recalculate it's bounds and Move inside QuadTree, which lead to more lags, i.e. it's not for real-time game

I'm 100% sure the lags due to initial qtree.Add, and then due to continuous qtree.Move

**Comment by splitice** [comment]
I suspect you may be right that the defaults are invalid. Pull request for better defaults or handling Infinity is welcome.

**Comment by ziplock9000** [comment]
Did this ever get fixed?

**Comment by splitice** [comment]
@ziplock9000 I've never received a pull request, no.

**Comment by StupydHors** [comment]
I would also like to express my distaste for the performance.
Using this library for a game with Unity and appending lists causes a lot of memory allocations.

**Comment by splitice** [comment]
Pull request for better defaults or handling Infinity is welcome.

**Comment by splitice** [comment]
Resolved with v1.0.3 via the removal of constructor defaults.

**Comment by Pro100AlexHell** [comment]
@splitice, have you solved the performance issues? it was the major issue, but not a concstructor parameters

**Comment by splitice** [comment]
There has never been any performane issues, only people who don't undestand the parameters and assumed the default parameters were both performant and fit for their speific application. The default constructor has been removed forcing users to supply a Root rectangle.

**Comment by Pro100AlexHell** [comment]
Do you missed my first post? It WAS the performance issue when use not default parameters, and the issue was in qtree.Add

> p.s. after a few hours I have found a case when Subdivision really works: in my project, I detect actual bounds of X and Y, and write constructor like
> new QuadTreeRectF<WorldObjectInQuadTree>(new System.Drawing.RectangleF(-8000, -8000, 16000, 16000));
> it's not good as we need to know exactly bounds
> 
> but it's work, i.e. assigns _childTl, _childTr , etc.
> 
> but performance is terrible..
> 100k objects is populates a few minutes into QuadTree
> after that initial population, objects start to moving and recalculate it's bounds and Move inside QuadTree, which lead to more lags, i.e. it's not for real-time game
> 
> I'm 100% sure the lags due to initial qtree.Add, and then due to continuous qtree.Move

**Comment by splitice** [comment]
Yes one root node is what will happen with an infinite sized rectangle. Supply a rectangle as is now required and subdivision (a /2 occurs).

The same as a node with more than max elements will occur if no suvduvisuon is possible (where more than 10 values exist at the same point)

All of these are properties of a quadtree. If that's not performance for you then your needs (or usage of the algorithm) don't fit the quadtree data type.
